# Generated by Django 2.2.4 on 2019-10-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bawarchi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ReserveDate',
            field=models.DateField(),
        ),
    ]
