# Generated by Django 2.2.4 on 2019-10-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bawarchi', '0002_auto_20191016_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ReserveDate',
            field=models.DateTimeField(),
        ),
    ]
