# Generated by Django 2.2.4 on 2019-10-18 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bawarchi', '0007_auto_20191017_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='NumberOfGuests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2019, 10, 17, 21, 14, 47, 126794)),
        ),
    ]
